# Generated by Django 5.0 on 2024-01-01 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_member_joined_date_member_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_ID', models.CharField(max_length=255)),
                ('customer_email', models.CharField(max_length=255)),
                ('order_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_ID', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('leftInStock', models.IntegerField(null=True)),
                ('stock_date', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='orders',
            name='Product_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.product'),
        ),
    ]
