# Generated by Django 5.0 on 2024-01-01 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders',
            new_name='order',
        ),
    ]
